version: "3"

services:
  db:
    restart: always
    hostname: auth-db
    image: postgres:14.2
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=root
    ports:
      - 5432:5432

volumes:
  my-db: